apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 labels:
   app: backend
spec:
 replicas: 1
 selector:
  matchLabels: 
   app: backend
 template:
  metadata:
   labels:
    app: backend
  spec:
    containers:
     - name: backend
       image: ghcr.io/eficode-academy/cat-serve:main
       ports:
        - containerPort = 9000

